# Generated by Django 5.1.3 on 2024-12-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_alter_register_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='email',
        ),
    ]
